### ISSUE TITLE
Hoofdbegrippen - 1e ervaringen na gebruik

### ISSUE THREAD

**Issue by DennisTheGit** [bp4mc2/bp4mc2-zvg#2]
Toegevoegd om inzicht te geven in de hoofdbegrippen, zijn:
1. boomstructuur met 'hoogste' begrippen
2. lijst met belangrijkste begrippen
3. wie/wat/hoe/met wie van 'laagste' begrippen 

Ik merk dat ik vooral 2 en 3 prettig vind werken en geen gebruik maak van 1. Maar, ik ken de taxonomie en weet waar ik wat zoeken moeten. Het kan alle 3 van waarde zijn en zou voor nu willen voorstellen ze allemaal te laten staan.

**Comment by ArjenSantema** [comment]
In zv.ttl de belangrijkste begrippen als skos:topConcepts gedefinieerd. Ook de 'belangrijkste' begrippen zoals koper en verkoper zijn gedefinieerd als topConcepts. Daarmee worden in de hiërarchie in begrippenXL op het hoogste niveau de 'hoogste' en de belangrijkste begrippen getoond.
